### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by benmccann**
Updates the `package-lock` to get rid of some warnings on the console

### CODE REVIEW

**Comment by Conduitry** [comment]
As a template, I don't think a lockfile belongs in here at all.

As a generic IE template, I'd argue `@beyonk/sapper-httpclient` also doesn't really belong here.

The command in the npm script to manually copy over the dev version of shimport also should be removed, and won't work on Windows anyway.

**Comment by benmccann** [comment]
I guess it depends if you think of it as a template or an example project. I'm fine either way

I just sent a PR for the shimport thing: https://github.com/antony/sapper-ie/pull/13

**Comment by antony** [comment]
The reason `@beyonk/sapper-httpclient` was in here is because it was a library which caused me specific trouble during my first attempt at making an IE-ready Sapper template. It can probably be replaced with some specific troublesome lines of JS now, or a `node_module` doing something similar. It's a way of testing that the babel config still works.

**Comment by Conduitry** [comment]
Woah this notification was a blast from the past.

**Comment by benmccann** [comment]
Yeah :laughing:  I was cleaning out my PR queue...

**Pull request closed without merging**
